Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus   = 2
  end
config.vbguest.auto_update = false

# config.vm.define "RevProxy" do |proxy|
#   proxy.vm.box = "debian/bookworm64"
#   proxy.vm.hostname = "database"
#   proxy.vm.network "private_network", ip: "192.168.56.13"
#   proxy.vm.network "forwarded_port", guest: 80, host: 80
#   proxy.vm.provision "ansible_local" do |ansible|
#     ansible.install = true
#     ansible.become  = true
#     ansible.playbook = "RevProxy.yml"
#     ansible.inventory_path = "inventory.ini"   
#     ansible.verbose = "v"
#   end
# end

  # ============================== DATABASE ==============================
  
  config.vm.define "database" do |db|
    db.vm.box = "debian/bookworm64"
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.network "forwarded_port", guest: 5432, host: 5433
    db.vm.provision "ansible_local" do |ansible|
      ansible.install = true
      ansible.become  = true
      ansible.playbook = "database.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit = "database"       
      ansible.verbose = "v"
    end
  end


  # =============================== BACKEND ==============================
  config.vm.define "backend" do |backend|
    backend.vm.box = "generic/ubuntu2204"
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.56.11"
    backend.vm.network "forwarded_port", guest: 8080, host: 8080
    backend.vm.synced_folder ".", "/vagrant"
    backend.vm.synced_folder "../../application/backend", "/app", mount_options: ["dmode=775,fmode=664"]
    backend.vm.provision "ansible_local" do |ans|
      ans.install = true
      ans.playbook = "backend.yml"
      ans.inventory_path = "inventory.ini"
  end
end

  # ============================== FRONTEND ==============================
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "generic/ubuntu2204"
    frontend.vm.hostname = "frontend"
    frontend.vm.network "private_network", ip: "192.168.56.10"
    frontend.vm.network "forwarded_port", guest: 4300, host: 4300
    frontend.vm.synced_folder ".", "/vagrant"
    frontend.vm.synced_folder "../../application/frontend", "/app", mount_options: ["uid=1000","gid=1000","dmode=775","fmode=775"]
    frontend.vm.provision "ansible_local" do |ansible|
      ansible.install = true
      ansible.playbook = "frontend.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit = "frontend"
    end
  end

  config.vm.define "build_machine" do |build_machine|
    build_machine.vm.box = "generic/ubuntu2204"
    build_machine.vm.hostname = "buildMachine"
    build_machine.vm.network "private_network", ip: "192.168.56.20"
    build_machine.vm.synced_folder ".", "/vagrant"
    build_machine.vm.synced_folder "build/shared", "/app", mount_options: ["uid=1000","gid=1000","dmode=775","fmode=775"]
    build_machine.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "build/build.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit = "build_machine"
      ansible.verbose = "v"
    end
  end 

  config.vm.define "repository_machine" do |repo|
    repo.vm.box = "debian/bookworm64"
    repo.vm.hostname = "repositoryMachine"
    repo.vm.network "private_network", ip: "192.168.56.21"
    repo.vm.synced_folder ".", "/vagrant"
    repo.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "repository.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.limit = "repository_machine"
      ansible.verbose = "v"
    end
  end
end